export type SourceCadence =
  | 'realtime'
  | 'delayed'
  | 'intraday'
  | 'daily'
  | 'weekly'
  | 'monthly'
  | 'historical'
  | 'research';

export type SourceTier = 1 | 2 | 3 | 4 | 5;

export interface SourceDefinition {
  sourceName: string;
  sourceType: string;
  url: string;
  docsUrl: string;
  authRequired: boolean;
  envKeys: string[];
  free: boolean;
  updateFrequency: string;
  historicalAvailability: string;
  realtime: boolean;
  delayed: boolean;
  cadence: SourceCadence;
  reliabilityScore: number;
  priority: number;
  fallback: string | null;
  tier: SourceTier;
  notes: string;
  notesAr: string;
}

export const SOURCE_REGISTRY: SourceDefinition[] = [
  {
    sourceName: 'gold-api.com',
    sourceType: 'spot_price',
    url: 'https://api.gold-api.com/price/XAU',
    docsUrl: 'https://gold-api.com/docs',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'seconds to minutes (provider timestamp required)',
    historicalAvailability: 'history/OHLC require provider API key',
    realtime: false,
    delayed: true,
    cadence: 'delayed',
    reliabilityScore: 62,
    priority: 1,
    fallback: 'currency-api-xau',
    tier: 3,
    notes: 'Third-party spot quote. Not an exchange feed. Never label LIVE unless timestamp is < 60s and provider claims streaming.',
    notesAr: 'سعر فوري من مزود ثالث. ليس تغذية بورصة. لا يُعرض كـ LIVE إلا بطابع زمني حديث.',
  },
  {
    sourceName: 'goldapi.io',
    sourceType: 'spot_price',
    url: 'https://www.goldapi.io/api/XAU/USD',
    docsUrl: 'https://www.goldapi.io/api-documentation',
    authRequired: true,
    envKeys: ['GOLDAPI_API_KEY'],
    free: true,
    updateFrequency: 'minutes (plan-dependent)',
    historicalAvailability: 'daily by date YYYYMMDD',
    realtime: false,
    delayed: true,
    cadence: 'delayed',
    reliabilityScore: 68,
    priority: 2,
    fallback: 'gold-api.com',
    tier: 3,
    notes: 'Optional paid/free-tier metals API. Auth header x-access-token. Used only when GOLDAPI_API_KEY is set.',
    notesAr: 'واجهة معادن اختيارية. لا تُستدعى بدون مفتاح.',
  },
  {
    sourceName: 'currency-api-xau',
    sourceType: 'fx_implied_gold',
    url: 'https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/usd.min.json',
    docsUrl: 'https://github.com/fawazahmed0/exchange-api',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'daily',
    historicalAvailability: 'daily via @YYYY-MM-DD from ~2020',
    realtime: false,
    delayed: true,
    cadence: 'daily',
    reliabilityScore: 70,
    priority: 3,
    fallback: 'currency-api-pages',
    tier: 3,
    notes: 'FX-implied XAU/USD (1 / usd.xau). Fallback: latest.currency-api.pages.dev. Not LBMA fix.',
    notesAr: 'ذهب مستنتج من أسعار الصرف اليومية. ليس تثبيت LBMA.',
  },
  {
    sourceName: 'currency-api-pages',
    sourceType: 'fx_implied_gold',
    url: 'https://latest.currency-api.pages.dev/v1/currencies/usd.min.json',
    docsUrl: 'https://github.com/fawazahmed0/exchange-api',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'daily',
    historicalAvailability: 'daily via date.currency-api.pages.dev',
    realtime: false,
    delayed: true,
    cadence: 'daily',
    reliabilityScore: 68,
    priority: 4,
    fallback: null,
    tier: 3,
    notes: 'Cloudflare Pages fallback for the same open currency dataset.',
    notesAr: 'مصدر احتياطي لنفس مجموعة أسعار الصرف المفتوحة.',
  },
  {
    sourceName: 'fred',
    sourceType: 'macro',
    url: 'https://api.stlouisfed.org/fred/series/observations',
    docsUrl: 'https://fred.stlouisfed.org/docs/api/fred/',
    authRequired: true,
    envKeys: ['FRED_API_KEY'],
    free: true,
    updateFrequency: 'daily to monthly by series',
    historicalAvailability: 'decades for Treasury, CPI, dollar, employment',
    realtime: false,
    delayed: true,
    cadence: 'daily',
    reliabilityScore: 95,
    priority: 1,
    fallback: 'fred-csv',
    tier: 1,
    notes: 'Official St. Louis Fed. LBMA gold series GOLDAMGBD228NLBM was delisted in 2022 and MUST NOT be requested.',
    notesAr: 'فيدرالي سانت لويس الرسمي. سلسلة الذهب اليومية نُزعت من FRED عام 2022 ولا تُطلب.',
  },
  {
    sourceName: 'fred-csv',
    sourceType: 'macro',
    url: 'https://fred.stlouisfed.org/graph/fredgraph.csv',
    docsUrl: 'https://fred.stlouisfed.org/docs/api/fred/',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'daily to monthly',
    historicalAvailability: 'same series as FRED',
    realtime: false,
    delayed: true,
    cadence: 'daily',
    reliabilityScore: 90,
    priority: 2,
    fallback: null,
    tier: 1,
    notes: 'Public FRED CSV download used when FRED_API_KEY is missing.',
    notesAr: 'تنزيل CSV العام من FRED عند غياب المفتاح.',
  },
  {
    sourceName: 'us-treasury',
    sourceType: 'rates',
    url: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml',
    docsUrl: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'daily (business days)',
    historicalAvailability: 'current year XML + archives',
    realtime: false,
    delayed: true,
    cadence: 'daily',
    reliabilityScore: 98,
    priority: 1,
    fallback: 'fred',
    tier: 1,
    notes: 'Official US Treasury par yield curve XML. Not a scrape of the HTML table.',
    notesAr: 'منحنى العائد الرسمي لوزارة الخزانة الأمريكية.',
  },
  {
    sourceName: 'cftc-cot',
    sourceType: 'positioning',
    url: 'https://www.cftc.gov/dea/newcot/deacot.txt',
    docsUrl: 'https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'weekly (Friday)',
    historicalAvailability: 'weekly files / open data',
    realtime: false,
    delayed: true,
    cadence: 'weekly',
    reliabilityScore: 92,
    priority: 1,
    fallback: null,
    tier: 1,
    notes: 'Official CFTC Commitments of Traders. Crowded longs are a warning, not automatically bullish.',
    notesAr: 'تقرير التزامات المتداولين الرسمي. التمركز المزدحم تحذير وليس إشارة صعود تلقائية.',
  },
  {
    sourceName: 'federal-reserve-rss',
    sourceType: 'news',
    url: 'https://www.federalreserve.gov/feeds/press_all.xml',
    docsUrl: 'https://www.federalreserve.gov/feeds/',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'as published',
    historicalAvailability: 'recent press items',
    realtime: false,
    delayed: false,
    cadence: 'research',
    reliabilityScore: 96,
    priority: 1,
    fallback: null,
    tier: 1,
    notes: 'Official Fed headlines/RSS only. No scraping of restricted news sites.',
    notesAr: 'عناوين الفيدرالي الرسمية فقط. بدون كشط مواقع إخبارية محظورة.',
  },
  {
    sourceName: 'world-gold-council-rss',
    sourceType: 'research',
    url: 'https://www.gold.org/news/rss',
    docsUrl: 'https://www.gold.org',
    authRequired: false,
    envKeys: [],
    free: true,
    updateFrequency: 'as published',
    historicalAvailability: 'research headlines',
    realtime: false,
    delayed: false,
    cadence: 'research',
    reliabilityScore: 88,
    priority: 2,
    fallback: null,
    tier: 2,
    notes: 'WGC research headlines. Historical WGC statistics are not realtime market data.',
    notesAr: 'عناوين أبحاث مجلس الذهب العالمي. ليست بيانات سوق لحظية.',
  },
  {
    sourceName: 'cme-group',
    sourceType: 'futures',
    url: 'https://www.cmegroup.com/markets/metals/precious/gold.html',
    docsUrl: 'https://www.cmegroup.com',
    authRequired: true,
    envKeys: ['CME_API_KEY'],
    free: false,
    updateFrequency: 'licensed realtime or delayed',
    historicalAvailability: 'licensed',
    realtime: false,
    delayed: true,
    cadence: 'delayed',
    reliabilityScore: 99,
    priority: 9,
    fallback: null,
    tier: 1,
    notes: 'Not implemented: redistribution of CME prices requires a license.',
    notesAr: 'غير مُنفَّذ: إعادة توزيع أسعار CME تتطلب ترخيصاً.',
  },
  {
    sourceName: 'world-gold-council-stats',
    sourceType: 'fundamental',
    url: 'https://www.gold.org/goldhub/data',
    docsUrl: 'https://www.gold.org/goldhub/data',
    authRequired: true,
    envKeys: [],
    free: false,
    updateFrequency: 'quarterly / monthly research',
    historicalAvailability: 'research tables after license/terms',
    realtime: false,
    delayed: false,
    cadence: 'monthly',
    reliabilityScore: 94,
    priority: 9,
    fallback: null,
    tier: 2,
    notes: 'ETF flows, CB buying, supply/demand require WGC Gold Hub access. Not scraped.',
    notesAr: 'تدفقات الصناديق ومشتريات البنوك المركزية تتطلب ترخيص Gold Hub. لا كشط.',
  },
];

export const FRED_SERIES = [
  { id: 'DGS2', label: 'US 2Y Treasury', unit: 'percent', cadence: 'daily' as const },
  { id: 'DGS5', label: 'US 5Y Treasury', unit: 'percent', cadence: 'daily' as const },
  { id: 'DGS10', label: 'US 10Y Treasury', unit: 'percent', cadence: 'daily' as const },
  { id: 'DGS30', label: 'US 30Y Treasury', unit: 'percent', cadence: 'daily' as const },
  { id: 'DFII10', label: 'US 10Y TIPS / real yield', unit: 'percent', cadence: 'daily' as const },
  { id: 'DTWEXBGS', label: 'Trade-weighted USD (broad)', unit: 'index', cadence: 'daily' as const },
  { id: 'DEXUSEU', label: 'USD/EUR', unit: 'fx', cadence: 'daily' as const },
  { id: 'DEXJPUS', label: 'USD/JPY', unit: 'fx', cadence: 'daily' as const },
  { id: 'DEXCHUS', label: 'USD/CNY', unit: 'fx', cadence: 'daily' as const },
  { id: 'DEXEGUS', label: 'USD/EGP', unit: 'fx', cadence: 'daily' as const },
  { id: 'FEDFUNDS', label: 'Fed funds effective (monthly)', unit: 'percent', cadence: 'monthly' as const },
  { id: 'DFF', label: 'Fed funds effective (daily)', unit: 'percent', cadence: 'daily' as const },
  { id: 'CPIAUCSL', label: 'CPI (index)', unit: 'index', cadence: 'monthly' as const },
  { id: 'CPILFESL', label: 'Core CPI (index)', unit: 'index', cadence: 'monthly' as const },
  { id: 'PCEPI', label: 'PCE price index', unit: 'index', cadence: 'monthly' as const },
  { id: 'PCEPILFE', label: 'Core PCE', unit: 'index', cadence: 'monthly' as const },
  { id: 'UNRATE', label: 'Unemployment rate', unit: 'percent', cadence: 'monthly' as const },
  { id: 'PAYEMS', label: 'Nonfarm payrolls', unit: 'thousands', cadence: 'monthly' as const },
  { id: 'ICSA', label: 'Initial jobless claims', unit: 'number', cadence: 'weekly' as const },
  { id: 'GDP', label: 'US GDP', unit: 'billions', cadence: 'quarterly' as const },
  { id: 'WALCL', label: 'Fed balance sheet', unit: 'millions', cadence: 'weekly' as const },
];
